"""Emit the browser UI's data bundle from a generated cohort.

Run: python3 scripts/export_ui_data.py [seed] [output]

WHY THE TEAM ORDERINGS ARE PRECOMPUTED HERE
-------------------------------------------
The browser UI re-runs deferred acceptance locally so that dragging someone
onto a team gives an instant, honest answer about who that displaces. That
means DA exists twice: once in matching.py and once in the page's JavaScript.

Two copies of an algorithm drift. The mitigation is to keep the *judgment* in
one place and duplicate only the mechanism:

  - Team preference orders are computed by scoring.py and baked into this
    bundle. They depend on a seeded SHA-256 tie-break that would be tedious and
    error-prone to reimplement in JS, and they never change in response to
    anything the UI can do — capacity edits and pins do not alter how a team
    ranks people. So the UI reads the real rankings rather than recreating them.

  - The DA loop itself is ~40 lines of queue manipulation with no tunable
    constants. That is the only part the page reimplements.

If you change scoring.py, re-run this script. The page's numbers come from
Python; only the seat-shuffling happens in the browser.
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from resumatch.generate import generate_cohort  # noqa: E402
from resumatch.taxonomy import (  # noqa: E402
    DOMAIN_PHRASES,
    DOMAINS,
    SKILL_DEFS,
)
from resumatch.scoring import (  # noqa: E402
    W_INTEREST,
    W_PREFERRED,
    W_REQUIRED,
    W_WISHLIST,
    WISHLIST_DECAY_PER_POSITION,
    WISHLIST_MIN_MULTIPLIER,
    build_scoring_context,
)


def _alias_map() -> dict[str, str]:
    """Every spelling that resolves to a canonical skill, including the
    canonical name itself and its space-separated form."""
    out: dict[str, str] = {}
    for canonical, (_domain, aliases) in SKILL_DEFS.items():
        out[canonical] = canonical
        out[canonical.replace("_", " ")] = canonical
        for alias in aliases:
            out[alias] = canonical
    return out


def export(seed: int = 42, output: str = "ui/data.js") -> None:
    cohort = generate_cohort(n_candidates=150, n_teams=20, seed=seed)
    ctx = build_scoring_context(cohort, seed=0)

    team_index = {t.id: i for i, t in enumerate(cohort.teams)}
    cand_index = {c.id: i for i, c in enumerate(cohort.candidates)}

    payload = {
        "seed": seed,
        "matchSeed": 0,
        "cohortHash": cohort.content_hash(),
        "weights": {
            "required": W_REQUIRED,
            "preferred": W_PREFERRED,
            "interest": W_INTEREST,
            "wishlist": W_WISHLIST,
            "wishlistDecay": WISHLIST_DECAY_PER_POSITION,
            "wishlistFloor": WISHLIST_MIN_MULTIPLIER,
        },
        "candidates": [
            {
                "id": c.id,
                "name": c.name,
                "skills": sorted(c.skills),
                "interests": sorted(c.interests),
                "prefs": [team_index[t] for t in c.ranked_team_ids],
            }
            for c in cohort.candidates
        ],
        "teams": [
            {
                "id": t.id,
                "name": t.name,
                "capacity": t.capacity,
                "domains": sorted(t.domain_tags),
                "required": sorted(t.required_skills),
                "preferred": sorted(t.preferred_skills),
                "wishlist": [cand_index[c] for c in t.wishlist if c in cand_index],
            }
            for t in cohort.teams
        ],
        # order[teamIdx] = candidate indices, best first, per scoring.py
        "order": [
            [cand_index[cid] for cid in ctx.team_order[t.id]] for t in cohort.teams
        ],
        # The skill vocabulary, shipped so the browser's resume intake speaks
        # exactly the same language as taxonomy.py. The matching *logic* is a
        # few lines of regex the browser repeats; the vocabulary itself stays
        # single-source here, which is the part that actually drifts — a skill
        # added in Python but missing in the browser would silently score a
        # real fit as zero on the intake screen only.
        "taxonomy": {
            "domains": list(DOMAINS),
            # alias (lowercase) -> canonical skill
            "aliases": _alias_map(),
            # canonical -> domain
            "skillDomain": {s: d for s, (d, _) in SKILL_DEFS.items()},
            "domainPhrases": {d: list(p) for d, p in DOMAIN_PHRASES.items()},
        },
    }

    os.makedirs(os.path.dirname(os.path.abspath(output)), exist_ok=True)
    with open(output, "w", encoding="utf-8") as fh:
        fh.write("// Generated by scripts/export_ui_data.py — do not edit by hand.\n")
        fh.write("// Team orderings come from resumatch/scoring.py so the UI cannot\n")
        fh.write("// silently disagree with the Python engine about who ranks where.\n")
        fh.write("window.RESUMATCH_DATA = ")
        json.dump(payload, fh, separators=(",", ":"))
        fh.write(";\n")

    size = os.path.getsize(output)
    print(
        f"Wrote {output} ({size / 1024:.0f} KB) — "
        f"{len(payload['candidates'])} candidates, {len(payload['teams'])} teams, "
        f"cohort {payload['cohortHash'][:12]}"
    )


if __name__ == "__main__":
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 42
    out = sys.argv[2] if len(sys.argv) > 2 else "ui/data.js"
    export(seed, out)
