// Skill extraction in the browser, using the vocabulary exported from
// resumatch/taxonomy.py.
//
// The *vocabulary* is not duplicated — aliases, domains and phrases all ship
// in data.js, generated by scripts/export_ui_data.py. Only the matching
// mechanism lives here, and it is a few lines of regex.
//
// That split matters: a skill added in Python but missing in the browser would
// silently score a real fit as zero on the intake screen and nowhere else,
// which is close to impossible to notice.

const TAX = window.RESUMATCH_DATA.taxonomy;

// Match a term as a standalone token.
//
// The lookarounds are asymmetric, and both halves are load-bearing:
//   behind  excludes "." so "js" inside "node.js" is not read as standalone
//   ahead   allows "." so a skill ending a sentence still matches
//
// That second point was a real bug in the Python version: excluding "." on
// both sides meant "deployed on Kubernetes." and "backed by PostgreSQL."
// matched nothing, because every resume ends its sentences. Most of the
// vocabulary was quietly unreachable. Keep this in step with taxonomy.py.
function boundaryPattern(term) {
  const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp("(?<![a-z0-9+#.])" + escaped + "(?![a-z0-9+#])", "i");
}

// Longest first, so multi-word aliases win over their constituent words.
const LOOKUP = Object.keys(TAX.aliases)
  .sort((a, b) => b.length - a.length)
  .map((alias) => ({ re: boundaryPattern(alias), canonical: TAX.aliases[alias] }));

const PHRASE_LOOKUP = Object.keys(TAX.domainPhrases).map((domain) => ({
  domain,
  patterns: TAX.domainPhrases[domain].map(boundaryPattern),
}));

/** Canonical skills found in free text. */
export function extractSkills(text) {
  const found = new Set();
  for (const entry of LOOKUP) {
    if (entry.re.test(text)) found.add(entry.canonical);
  }
  return Array.from(found).sort();
}

/**
 * Domain interests, from explicit phrases plus the domains of found skills.
 *
 * Someone with five backend skills is interested in backend whether or not
 * they wrote the word, so skill domains feed in automatically.
 */
export function extractInterests(text, skills) {
  const lowered = text.toLowerCase();
  const found = new Set();
  for (const entry of PHRASE_LOOKUP) {
    if (entry.patterns.some((p) => p.test(lowered))) found.add(entry.domain);
  }
  for (const skill of skills) {
    const domain = TAX.skillDomain[skill];
    if (domain) found.add(domain);
  }
  return Array.from(found).sort();
}

/** Normalize one user-supplied term, or null when it is not in the vocabulary. */
export function normalize(term) {
  return TAX.aliases[String(term).trim().toLowerCase()] || null;
}

export function pretty(skill) {
  return String(skill).replace(/_/g, " ");
}

/**
 * Parse resume text into the shape the scorer needs, plus anything a human
 * should know about the parse.
 *
 * Warnings are not decoration. A silent bad parse is the worst outcome here:
 * the match still runs and still looks defensible, it is just quietly wrong
 * for that person.
 */
export function parseResume(text) {
  const skills = extractSkills(text);
  const interests = extractInterests(text, skills);
  const warnings = [];

  if (text.trim().length < 120) {
    warnings.push("This is very short for a resume — check the whole thing was pasted.");
  }
  if (!skills.length) {
    warnings.push(
      "No recognized skills found. This candidate would score 0.00 against every team " +
        "and could only be placed by the fallback round."
    );
  } else if (skills.length < 3) {
    warnings.push(
      `Only ${skills.length} skill${skills.length === 1 ? "" : "s"} recognized — ` +
        "matching will be weakly informed."
    );
  }

  return { skills, interests, warnings, name: guessName(text) };
}

const CONTACT_HINT = /[@\d]|https?:\/\/|linkedin|github/i;

/**
 * Best-effort name from the top of a resume. Display only — nothing in
 * scoring reads it, and that is deliberate (see README §9).
 */
export function guessName(text) {
  const lines = text.split("\n").slice(0, 6);
  for (const line of lines) {
    const stripped = line.trim();
    if (!stripped || stripped.length > 48) continue;
    if (CONTACT_HINT.test(stripped)) continue;
    const words = stripped.split(/\s+/);
    if (words.length > 1 && words.length <= 4 && words.every((w) => /^[a-z]/i.test(w))) {
      return stripped === stripped.toUpperCase()
        ? stripped.replace(/\w\S*/g, (w) => w[0] + w.slice(1).toLowerCase())
        : stripped;
    }
  }
  return "";
}
